### ISSUE TITLE
This repository is not nessicarily needed.

### ISSUE THREAD

**Issue by AraHaan** [fuzeman/ZLIB.NET_Free#1]
With my zlib.managed fork of zlib.net I provide better and more fixes that are not in here and unfortunately only way I was able to publish the fixes to nuget.org was to rename it to that.

https://github.com/Elskom/zlib.managed/

Thanks for your understanding. Make sure those who forked this know that my zlib.managed contains a lot of bug fixes and also provides a helper class so you do not have to use the ``ZInputStream`` and ``ZOutputStream``'s yourself called ``MemoryZlib`` which allows you to ``Compress``, and ``Decompress`` the data similar using the byte array of the actual data in the first parameter, and the last one is an inlined variable declaration that will hold the result of the operation.

Edit: I see who did for this,  @alexribek, and @dregula (Sorry for mentions just wanted you guys to know so that way you guys would know of the bugs I fixed from the raw version 1.04 you guys use).

**Comment by fuzeman** [comment]
I'm archiving this repository now.
